name: alio_sub_button
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  assets:
    - assets/images/calendar.png
  uses-material-design: true
  
